# This is a basic workflow to help you get started with Actions

name: Pull Request on 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: run github workspace
        run: echo $GITHUB_WORKSPACE
      
      - name: Run github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: run github event
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_EVENT"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "$github.event" && echo "$github.event.comment.body"
        
      - name: run show testNg
        if: contains(github.event.comment.body, 'testng')
        run: echo testng
      - name: run issue
        if: contains(github.event.comment.html_url, '/pull/')
        run: echo pull issue
